# Configure Netlify build settings
[build]
  command = "npm install --legacy-peer-deps --force && npm run postinstall && npm run build"
  publish = "dist"

# Use our custom dependency fix plugin
[[plugins]]
  package = "./netlify-plugin-dependency-fix"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize build
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  
# Enable dependency installation output for debugging
[build.processing]
  skip_processing = false 