# Configure Netlify build settings
[build]
  command = "npm run build:netlify"
  publish = "dist"

# Use our custom dependency fix plugin
[[plugins]]
  package = "/opt/build/repo/netlify-plugin-dependency-fix"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize build
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  CI = "true"
  NETLIFY_USE_YARN = "false"
  
# Enable dependency installation output for debugging
[build.processing]
  skip_processing = false 